import Head from 'next/head';
import './globals.css';

export const metadata = {
  title: 'henchlegal',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        {/* Add other head elements if needed */}
      </Head>
      <body>{children}</body>
    </html>
  );
}
